# .streamlit/secrets.toml

AZURE_STORAGE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=vocalstorage57242;AccountKey=KVDT+9njA/xJI8V7yP1MIFXtAncDUSNLINWAA8GbFijBEkO0OdjdisJiLcdevu2uDhB3a8Xdh5XH+AStnsRE4A==;EndpointSuffix=core.windows.net"
AZURE_CONTAINER_NAME = "audios"

COSMOS_DB_CONN_STRING = "AccountEndpoint=https://vocalcosmos57242.documents.azure.com:443/;AccountKey=gJ8i4StBD94zPYYxntpJY9sGJZohWFR4xaQN4Yf1UuFETJj8TG5Q6vOQPe1gWCnzG7gW2rISIIJYACDbPXs4Ig==;"
COSMOS_DB_NAME = "TranscricoesDB"
COSMOS_DB_CONTAINER_NAME = "Transcricoes"
